<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="HistoricoPeleas.aspx.cs" Inherits="TTT2RanksManager.HistoricoPeleas" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="frmHistorico" runat="server">
    <div>    
        <asp:GridView ID="gvHistoricoPeleas" runat="server" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            DataSourceID="SqlDSPeleas" EnableModelValidation="True" 
            AutoGenerateColumns="False" DataKeyNames="peleaId">
            <Columns>
                <asp:BoundField DataField="peleaId" HeaderText="ID"/>
                <asp:TemplateField HeaderText="Peleador1" SortExpression="char1Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" runat="server" 
                            DataSourceID="SQLDSPeleador1" DataTextField="name" DataValueField="charId" 
                            SelectedValue='<%# Bind("char1Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPeleador1" runat="server" Text='<%# Bind("Peleador1") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Rango1" SortExpression="rank1Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRango1" runat="server" 
                            DataSourceID="SQLDSRango" DataTextField="nombre" DataValueField="rankId" 
                            SelectedValue='<%# Bind("rank1Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRango1" runat="server" Text='<%# Bind("rango1") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Peleador2" SortExpression="char2Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlPeleador2" runat="server" 
                            DataSourceID="SQLDSPeleador1" DataTextField="name" DataValueField="charId" 
                            SelectedValue='<%# Bind("char2Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPeleador2" runat="server" Text='<%# Bind("Peleador2") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Rango2" SortExpression="rank2Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRango2" runat="server" 
                            DataSourceID="SQLDSRango" DataTextField="nombre" DataValueField="rankId" 
                            SelectedValue='<%# Bind("rank2Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRango2" runat="server" Text='<%# Bind("rango2") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Psn" SortExpression="rivalId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlNombreRival" runat="server" 
                            DataSourceID="SQLDSRival" DataTextField="psn" DataValueField="rivalId" 
                            SelectedValue='<%# Bind("rivalId") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPsn" runat="server" Text='<%# Bind("psn") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="R. Peleador1" SortExpression="rivalChar1Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRivalPeleador1" runat="server" 
                            DataSourceID="SQLDSPeleador1" DataTextField="name" DataValueField="charId" 
                            SelectedValue='<%# Bind("rivalChar1Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRivalChar1" runat="server" Text='<%# Bind("rivalChar1") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>


                <asp:TemplateField HeaderText="RangoRival1" SortExpression="rivalRank1">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRangoRival1" runat="server" 
                            DataSourceID="SQLDSRango" DataTextField="nombre" DataValueField="rankId" 
                            SelectedValue='<%# Bind("rivalRank1") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRRango1" runat="server" Text='<%# Bind("rrango1") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="R. Peleador2" SortExpression="rivalChar2Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRivalPeleador2" runat="server" 
                            DataSourceID="SQLDSPeleador1" DataTextField="name" DataValueField="charId" 
                            SelectedValue='<%# Bind("rivalChar2Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRivalChar2" runat="server" Text='<%# Bind("rivalChar2") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="RangoRival2" SortExpression="rivalRank2">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlRangoRival2" runat="server" 
                            DataSourceID="SQLDSRango" DataTextField="nombre" DataValueField="rankId" 
                            SelectedValue='<%# Bind("rivalRank2") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRRango2" runat="server" Text='<%# Bind("rrango2") %>'></asp:Label>
                    </ItemTemplate>                    
                </asp:TemplateField>

                <asp:BoundField DataField="puntos" HeaderText="Ptos" />

                <asp:BoundField DataField="promoBattle" HeaderText="IsPromo" />
                <asp:BoundField DataField="demoBattle" HeaderText="IsDemo" />
                <asp:BoundField DataField="promoted" HeaderText="wasPromoted" />
                <asp:BoundField DataField="demoted" HeaderText="wasDemoted" />               
                <asp:BoundField DataField="promoBattle2" HeaderText="IsPromo2" />
                <asp:BoundField DataField="demoBattle2" HeaderText="IsDemo2" />
                <asp:BoundField DataField="promoted2" HeaderText="wasPromoted2" />
                <asp:BoundField DataField="demoted2" HeaderText="wasDemoted2" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDSPeleas" runat="server" 
            ConnectionString="<%$ ConnectionStrings:TekkenCnn %>" 
            ProviderName="System.Data.SqlClient" 
            SelectCommand="SELECT Peleas.peleaId, 
Peleas.fecha, 
Peleas.char1Id, 
p1.name AS Peleador1,
Peleas.rank1Id,
r1.nombre as rango1,
Peleas.char2Id, 
p2.name AS Peleador2, 
Peleas.rank2Id,
r1.nombre as rango2,
Peleas.rivalId, 
Rivales.psn, 
Peleas.rivalChar1Id, 
rp1.name AS rivalChar1, 
Peleas.rivalRank1,
rr1.nombre as rrango1,
Peleas.rivalChar2Id, 
rp2.name AS rivalChar2, 
Peleas.rivalRank2, 
rr2.nombre as rrango2,
Peleas.puntos, 
Peleas.promoBattle, 
Peleas.demoBattle, 
Peleas.promoted, 
Peleas.demoted, 
Peleas.promoBattle2,
Peleas.demoBattle2,
Peleas.promoted2,
Peleas.demoted2
FROM Peleas 
INNER JOIN Rivales 
ON Peleas.rivalId = Rivales.rivalId 
LEFT OUTER JOIN Peleadores AS rp2 
ON Peleas.rivalChar2Id = rp2.charId 
LEFT OUTER JOIN Peleadores AS rp1 
ON Peleas.rivalChar1Id = rp1.charId 
LEFT OUTER JOIN Peleadores AS p2 
ON Peleas.char2Id = p2.charId 
LEFT OUTER JOIN Peleadores AS p1 
ON Peleas.char1Id = p1.charId 
LEFT JOIN Rangos as r1
ON R1.rankId = Peleas.rank1Id
LEFT JOIN Rangos as r2
ON R2.rankId = Peleas.rank2Id
LEFT JOIN Rangos as rr1
ON rr1.rankId = Peleas.rivalRank1
LEFT JOIN Rangos as rr2
ON rr2.rankId = Peleas.rivalRank2
ORDER BY Peleas.peleaId DESC"
            DeleteCommand="DELETE FROM Peleas WHERE peleaId=@peleaId"
            UpdateCommand="UPDATE Peleas set char1Id=@char1Id, char2Id=@char2Id,rivalChar1Id=@rivalChar1Id,rivalChar2Id=@rivalChar2Id, puntos=@puntos WHERE peleaId=@peleaId">
        </asp:SqlDataSource>
    
    </div>

    <asp:SqlDataSource ID="SQLDSPeleador1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:TekkenCnn %>" 
        SelectCommand="SELECT DISTINCT [charId], [name] FROM [Peleadores]" 
        ProviderName="<%$ ConnectionStrings:TekkenCnn.ProviderName %>">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SQLDSRival" runat="server" 
        ConnectionString="<%$ ConnectionStrings:TekkenCnn %>" 
        SelectCommand="SELECT DISTINCT [rivalId], [psn] FROM [Rivales] ORDER BY psn" 
        ProviderName="<%$ ConnectionStrings:TekkenCnn.ProviderName %>">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SQLDSRango" runat="server" 
        ConnectionString="<%$ ConnectionStrings:TekkenCnn %>" 
        SelectCommand="SELECT DISTINCT rankId, nombre FROM Rangos ORDER BY rankId" 
        ProviderName="<%$ ConnectionStrings:TekkenCnn.ProviderName %>">
    </asp:SqlDataSource>
    </form>
</body>
</html>
